# action.yaml
name: "Wick Push"
description: "Github action for pushing wick packages for distribution to supported platforms such as https://registry.candle.dev"
branding:
  icon: "layers"
  color: "orange"
inputs:
  path:
    description: "Path to the main wick manifest file.  Usually the file name is `app.wick` or `component.wick`.  This must contain the registry configuration details in the `package` section."
    required: true
    default: "app.wick"
  username:
    description: "Username for registry configured in the Wick manifest"
    required: true
  password:
    description: "Password for registry configured in the Wick manifest"
    required: true
  tags:
    description: "Space-separated list of additional tags to apply to the image. This is optional as push will always set the tag to the version in the manifest."
    required: false
outputs:
  reference:
    description: "The image reference that was pushed"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.tags }}
