on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: job to test push action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use root action
        uses: ./ # Uses an action in the root directory
        id: push
        with:
          path: ./tests/test_app.wick
          username: ${{ secrets.CANDLE_REGISTRY_USERNAME }}
          password: ${{ secrets.CANDLE_REGISTRY_PASSWORD }}
          tags: latest abc123 123456
      - name: Print push output
        run: 'echo "Push output: ${{ steps.push.outputs.reference }}"'
